### ISSUE TITLE
Compilation error with {enum: ["+"]}

### ISSUE THREAD

**Issue by michaelmior** [corvus-dotnet/Corvus.JsonSchema#469]
The generated code for the following schema fails to compile with version 4.0.0-preview.25.

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "enum": ["+"]
}
```
```
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(61,31): error CS1519: Invalid token '{' in class, record, struct, or interface member declaration [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(61,36): error CS1519: Invalid token ';' in class, record, struct, or interface member declaration [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(61,40): error CS1519: Invalid token '=' in class, record, struct, or interface member declaration [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(61,74): error CS1519: Invalid token '(' in class, record, struct, or interface member declaration [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(61,75): error CS8124: Tuple must contain at least two elements. [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(61,76): error CS1519: Invalid token ';' in class, record, struct, or interface member declaration [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]
/home/mmior/apps/jsonschema-benchmark/implementations/corvus/Schema.Validate.cs(139,1): error CS1022: Type or namespace definition, or end-of-file expected [/home/mmior/apps/jsonschema-benchmark/implementations/corvus/bench.csproj]

Build FAILED.
```

**Comment by mwadams** [comment]
This is a regression in the naming heuristic. We lost the fallback for identifiers that resolve to zero characters.

**Comment by mwadams** [comment]
Added support for translating single non-letter characters in the ASCII range to names.

Reinstated support for an empty identifier fallback name.

Fixed in V4.0.0-preview.27.

**Comment by michaelmior** [comment]
@mwadams Change `+` to `++` in the example above and this still fails.

**Comment by michaelmior** [comment]
The example below may be another instance of basically the same.

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    ".*": {}
  }
}
```

**Comment by mwadams** [comment]
That is the same... Curses!

**Comment by mwadams** [comment]
Stupid mistake, and didn't test for it.

Now sans stupid mistake, with test!

**Comment by mwadams** [comment]
v4.0.0-preview.28 will appear in about 30 minutes.
